[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
prize_pool_program = "DLo6qSd1fZ4D2T5cyeuDKSSWjgPcdGxwKVjTojEuL3N4"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
